// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/relay/discoverypb/discovery.proto

package discoverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        []byte                 `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"` // JSON-serialized a2a AgentCard
	Provenance    *Provenance            `protobuf:"bytes,2,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Visibility    *Visibility            `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	TtlNanos      int64                  `protobuf:"varint,4,opt,name=ttl_nanos,json=ttlNanos,proto3" json:"ttl_nanos,omitempty"` // TTL as signed nanoseconds
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                   // monotonic version within origin relay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryEnvelope) Reset() {
	*x = DiscoveryEnvelope{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryEnvelope) ProtoMessage() {}

func (x *DiscoveryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryEnvelope.ProtoReflect.Descriptor instead.
func (*DiscoveryEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryEnvelope) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *DiscoveryEnvelope) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *DiscoveryEnvelope) GetVisibility() *Visibility {
	if x != nil {
		return x.Visibility
	}
	return nil
}

func (x *DiscoveryEnvelope) GetTtlNanos() int64 {
	if x != nil {
		return x.TtlNanos
	}
	return 0
}

func (x *DiscoveryEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Provenance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginRelayId  string                 `protobuf:"bytes,1,opt,name=origin_relay_id,json=originRelayId,proto3" json:"origin_relay_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PublishedAt    int64                  `protobuf:"varint,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`         // unix nanoseconds at origin relay
	PublisherAgent string                 `protobuf:"bytes,4,opt,name=publisher_agent,json=publisherAgent,proto3" json:"publisher_agent,omitempty"` // agent ID, or "system" for operator
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                 // Ed25519 by origin relay CA key
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *Provenance) GetOriginRelayId() string {
	if x != nil {
		return x.OriginRelayId
	}
	return ""
}

func (x *Provenance) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Provenance) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Provenance) GetPublisherAgent() string {
	if x != nil {
		return x.PublisherAgent
	}
	return ""
}

func (x *Provenance) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Visibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`         // tenant_private | tenant_allowlisted | global_public
	Allowlist     []string               `protobuf:"bytes,2,rep,name=allowlist,proto3" json:"allowlist,omitempty"` // tenant IDs allowed when scope = tenant_allowlisted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Visibility) Reset() {
	*x = Visibility{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visibility) ProtoMessage() {}

func (x *Visibility) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visibility.ProtoReflect.Descriptor instead.
func (*Visibility) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *Visibility) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Visibility) GetAllowlist() []string {
	if x != nil {
		return x.Allowlist
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *DiscoveryEnvelope     `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Withdraw      bool                   `protobuf:"varint,2,opt,name=withdraw,proto3" json:"withdraw,omitempty"` // true = tombstone/withdraw, not publish
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *PushRequest) GetEnvelope() *DiscoveryEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PushRequest) GetWithdraw() bool {
	if x != nil {
		return x.Withdraw
	}
	return false
}

type PushResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // e.g. "version_too_low", "invalid_signature"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *PushResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type PullRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestingRelayId string                 `protobuf:"bytes,1,opt,name=requesting_relay_id,json=requestingRelayId,proto3" json:"requesting_relay_id,omitempty"`
	SinceVersion      uint64                 `protobuf:"varint,2,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"` // only records newer than this
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *PullRequest) GetRequestingRelayId() string {
	if x != nil {
		return x.RequestingRelayId
	}
	return ""
}

func (x *PullRequest) GetSinceVersion() uint64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

// Health/liveness probe (ADR §2.5).
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_discoverypb_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_relay_discoverypb_discovery_proto_rawDescGZIP(), []int{7}
}

var File_internal_relay_discoverypb_discovery_proto protoreflect.FileDescriptor

const file_internal_relay_discoverypb_discovery_proto_rawDesc = "" +
	"\n" +
	"*internal/relay/discoverypb/discovery.proto\x12\x10oap.discovery.v1\"\xde\x01\n" +
	"\x11DiscoveryEnvelope\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\x12<\n" +
	"\n" +
	"provenance\x18\x02 \x01(\v2\x1c.oap.discovery.v1.ProvenanceR\n" +
	"provenance\x12<\n" +
	"\n" +
	"visibility\x18\x03 \x01(\v2\x1c.oap.discovery.v1.VisibilityR\n" +
	"visibility\x12\x1b\n" +
	"\tttl_nanos\x18\x04 \x01(\x03R\bttlNanos\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"\xbb\x01\n" +
	"\n" +
	"Provenance\x12&\n" +
	"\x0forigin_relay_id\x18\x01 \x01(\tR\roriginRelayId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fpublished_at\x18\x03 \x01(\x03R\vpublishedAt\x12'\n" +
	"\x0fpublisher_agent\x18\x04 \x01(\tR\x0epublisherAgent\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"@\n" +
	"\n" +
	"Visibility\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1c\n" +
	"\tallowlist\x18\x02 \x03(\tR\tallowlist\"j\n" +
	"\vPushRequest\x12?\n" +
	"\benvelope\x18\x01 \x01(\v2#.oap.discovery.v1.DiscoveryEnvelopeR\benvelope\x12\x1a\n" +
	"\bwithdraw\x18\x02 \x01(\bR\bwithdraw\"U\n" +
	"\fPushResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\"b\n" +
	"\vPullRequest\x12.\n" +
	"\x13requesting_relay_id\x18\x01 \x01(\tR\x11requestingRelayId\x12#\n" +
	"\rsince_version\x18\x02 \x01(\x04R\fsinceVersion\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse2\xfe\x01\n" +
	"\x13DiscoveryFederation\x12K\n" +
	"\n" +
	"PushRecord\x12\x1d.oap.discovery.v1.PushRequest\x1a\x1e.oap.discovery.v1.PushResponse\x12S\n" +
	"\vPullRecords\x12\x1d.oap.discovery.v1.PullRequest\x1a#.oap.discovery.v1.DiscoveryEnvelope0\x01\x12E\n" +
	"\x04Ping\x12\x1d.oap.discovery.v1.PingRequest\x1a\x1e.oap.discovery.v1.PingResponseBKZIgithub.com/openagentplatform/openagentplatform/internal/relay/discoverypbb\x06proto3"

var (
	file_internal_relay_discoverypb_discovery_proto_rawDescOnce sync.Once
	file_internal_relay_discoverypb_discovery_proto_rawDescData []byte
)

func file_internal_relay_discoverypb_discovery_proto_rawDescGZIP() []byte {
	file_internal_relay_discoverypb_discovery_proto_rawDescOnce.Do(func() {
		file_internal_relay_discoverypb_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_relay_discoverypb_discovery_proto_rawDesc), len(file_internal_relay_discoverypb_discovery_proto_rawDesc)))
	})
	return file_internal_relay_discoverypb_discovery_proto_rawDescData
}

var file_internal_relay_discoverypb_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_relay_discoverypb_discovery_proto_goTypes = []any{
	(*DiscoveryEnvelope)(nil), // 0: oap.discovery.v1.DiscoveryEnvelope
	(*Provenance)(nil),        // 1: oap.discovery.v1.Provenance
	(*Visibility)(nil),        // 2: oap.discovery.v1.Visibility
	(*PushRequest)(nil),       // 3: oap.discovery.v1.PushRequest
	(*PushResponse)(nil),      // 4: oap.discovery.v1.PushResponse
	(*PullRequest)(nil),       // 5: oap.discovery.v1.PullRequest
	(*PingRequest)(nil),       // 6: oap.discovery.v1.PingRequest
	(*PingResponse)(nil),      // 7: oap.discovery.v1.PingResponse
}
var file_internal_relay_discoverypb_discovery_proto_depIdxs = []int32{
	1, // 0: oap.discovery.v1.DiscoveryEnvelope.provenance:type_name -> oap.discovery.v1.Provenance
	2, // 1: oap.discovery.v1.DiscoveryEnvelope.visibility:type_name -> oap.discovery.v1.Visibility
	0, // 2: oap.discovery.v1.PushRequest.envelope:type_name -> oap.discovery.v1.DiscoveryEnvelope
	3, // 3: oap.discovery.v1.DiscoveryFederation.PushRecord:input_type -> oap.discovery.v1.PushRequest
	5, // 4: oap.discovery.v1.DiscoveryFederation.PullRecords:input_type -> oap.discovery.v1.PullRequest
	6, // 5: oap.discovery.v1.DiscoveryFederation.Ping:input_type -> oap.discovery.v1.PingRequest
	4, // 6: oap.discovery.v1.DiscoveryFederation.PushRecord:output_type -> oap.discovery.v1.PushResponse
	0, // 7: oap.discovery.v1.DiscoveryFederation.PullRecords:output_type -> oap.discovery.v1.DiscoveryEnvelope
	7, // 8: oap.discovery.v1.DiscoveryFederation.Ping:output_type -> oap.discovery.v1.PingResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_relay_discoverypb_discovery_proto_init() }
func file_internal_relay_discoverypb_discovery_proto_init() {
	if File_internal_relay_discoverypb_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_relay_discoverypb_discovery_proto_rawDesc), len(file_internal_relay_discoverypb_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_relay_discoverypb_discovery_proto_goTypes,
		DependencyIndexes: file_internal_relay_discoverypb_discovery_proto_depIdxs,
		MessageInfos:      file_internal_relay_discoverypb_discovery_proto_msgTypes,
	}.Build()
	File_internal_relay_discoverypb_discovery_proto = out.File
	file_internal_relay_discoverypb_discovery_proto_goTypes = nil
	file_internal_relay_discoverypb_discovery_proto_depIdxs = nil
}
