// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: internal/relay/discoverypb/discovery.proto

package discoverypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryFederation_PushRecord_FullMethodName  = "/oap.discovery.v1.DiscoveryFederation/PushRecord"
	DiscoveryFederation_PullRecords_FullMethodName = "/oap.discovery.v1.DiscoveryFederation/PullRecords"
	DiscoveryFederation_Ping_FullMethodName        = "/oap.discovery.v1.DiscoveryFederation/Ping"
)

// DiscoveryFederationClient is the client API for DiscoveryFederation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryFederationClient interface {
	// Push: origin relay notifies peers of a new/updated/withdrawn record.
	PushRecord(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// Pull: a relay requests the peer's record set (reconciliation).
	PullRecords(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiscoveryEnvelope], error)
	// Ping: health check for peer liveness.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type discoveryFederationClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryFederationClient(cc grpc.ClientConnInterface) DiscoveryFederationClient {
	return &discoveryFederationClient{cc}
}

func (c *discoveryFederationClient) PushRecord(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, DiscoveryFederation_PushRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryFederationClient) PullRecords(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiscoveryEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiscoveryFederation_ServiceDesc.Streams[0], DiscoveryFederation_PullRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRequest, DiscoveryEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryFederation_PullRecordsClient = grpc.ServerStreamingClient[DiscoveryEnvelope]

func (c *discoveryFederationClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DiscoveryFederation_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryFederationServer is the server API for DiscoveryFederation service.
// All implementations must embed UnimplementedDiscoveryFederationServer
// for forward compatibility.
type DiscoveryFederationServer interface {
	// Push: origin relay notifies peers of a new/updated/withdrawn record.
	PushRecord(context.Context, *PushRequest) (*PushResponse, error)
	// Pull: a relay requests the peer's record set (reconciliation).
	PullRecords(*PullRequest, grpc.ServerStreamingServer[DiscoveryEnvelope]) error
	// Ping: health check for peer liveness.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDiscoveryFederationServer()
}

// UnimplementedDiscoveryFederationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryFederationServer struct{}

func (UnimplementedDiscoveryFederationServer) PushRecord(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushRecord not implemented")
}
func (UnimplementedDiscoveryFederationServer) PullRecords(*PullRequest, grpc.ServerStreamingServer[DiscoveryEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method PullRecords not implemented")
}
func (UnimplementedDiscoveryFederationServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDiscoveryFederationServer) mustEmbedUnimplementedDiscoveryFederationServer() {}
func (UnimplementedDiscoveryFederationServer) testEmbeddedByValue()                             {}

// UnsafeDiscoveryFederationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryFederationServer will
// result in compilation errors.
type UnsafeDiscoveryFederationServer interface {
	mustEmbedUnimplementedDiscoveryFederationServer()
}

func RegisterDiscoveryFederationServer(s grpc.ServiceRegistrar, srv DiscoveryFederationServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryFederationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryFederation_ServiceDesc, srv)
}

func _DiscoveryFederation_PushRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryFederationServer).PushRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryFederation_PushRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryFederationServer).PushRecord(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryFederation_PullRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryFederationServer).PullRecords(m, &grpc.GenericServerStream[PullRequest, DiscoveryEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryFederation_PullRecordsServer = grpc.ServerStreamingServer[DiscoveryEnvelope]

func _DiscoveryFederation_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryFederationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryFederation_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryFederationServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryFederation_ServiceDesc is the grpc.ServiceDesc for DiscoveryFederation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryFederation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oap.discovery.v1.DiscoveryFederation",
	HandlerType: (*DiscoveryFederationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRecord",
			Handler:    _DiscoveryFederation_PushRecord_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DiscoveryFederation_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullRecords",
			Handler:       _DiscoveryFederation_PullRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/relay/discoverypb/discovery.proto",
}
