/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRecordingsIndexRouteImport } from './routes/shell-recordings/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PatchesIndexRouteImport } from './routes/patches/index'
import { Route as ChecksIndexRouteImport } from './routes/checks/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as A2aIndexRouteImport } from './routes/a2a/index'
import { Route as ShellRecordingsSessionIdRouteImport } from './routes/shell-recordings/$sessionId'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsSsoRouteImport } from './routes/settings/sso'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsAuditLogRouteImport } from './routes/settings/audit-log'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as ScriptsNewRouteImport } from './routes/scripts/new'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts/$scriptId'
import { Route as PoliciesPolicyIdRouteImport } from './routes/policies/$policyId'
import { Route as PatchesJobIdRouteImport } from './routes/patches/$jobId'
import { Route as ChecksCheckIdRouteImport } from './routes/checks/$checkId'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts/$alertId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as A2aTasksRouteImport } from './routes/a2a/tasks'
import { Route as A2aCostsRouteImport } from './routes/a2a/costs'
import { Route as AgentsAgentIdShellRouteImport } from './routes/agents/$agentId/shell'
import { Route as A2aTasksTaskIdRouteImport } from './routes/a2a/tasks/$taskId'
import { Route as A2aAgentsNameRouteImport } from './routes/a2a/agents/$name'
import { Route as ScriptsScriptIdRunsRunIdRouteImport } from './routes/scripts/$scriptId/runs/$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRecordingsIndexRoute = ShellRecordingsIndexRouteImport.update({
  id: '/shell-recordings/',
  path: '/shell-recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchesIndexRoute = PatchesIndexRouteImport.update({
  id: '/patches/',
  path: '/patches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksIndexRoute = ChecksIndexRouteImport.update({
  id: '/checks/',
  path: '/checks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aIndexRoute = A2aIndexRouteImport.update({
  id: '/a2a/',
  path: '/a2a/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRecordingsSessionIdRoute =
  ShellRecordingsSessionIdRouteImport.update({
    id: '/shell-recordings/$sessionId',
    path: '/shell-recordings/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSsoRoute = SettingsSsoRouteImport.update({
  id: '/settings/sso',
  path: '/settings/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsNewRoute = ScriptsNewRouteImport.update({
  id: '/scripts/new',
  path: '/scripts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPolicyIdRoute = PoliciesPolicyIdRouteImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchesJobIdRoute = PatchesJobIdRouteImport.update({
  id: '/patches/$jobId',
  path: '/patches/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksCheckIdRoute = ChecksCheckIdRouteImport.update({
  id: '/checks/$checkId',
  path: '/checks/$checkId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aTasksRoute = A2aTasksRouteImport.update({
  id: '/a2a/tasks',
  path: '/a2a/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aCostsRoute = A2aCostsRouteImport.update({
  id: '/a2a/costs',
  path: '/a2a/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdShellRoute = AgentsAgentIdShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const A2aTasksTaskIdRoute = A2aTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => A2aTasksRoute,
} as any)
const A2aAgentsNameRoute = A2aAgentsNameRouteImport.update({
  id: '/a2a/agents/$name',
  path: '/a2a/agents/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRunsRunIdRoute =
  ScriptsScriptIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => ScriptsScriptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/a2a/costs': typeof A2aCostsRoute
  '/a2a/tasks': typeof A2aTasksRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/checks/$checkId': typeof ChecksCheckIdRoute
  '/patches/$jobId': typeof PatchesJobIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRouteWithChildren
  '/scripts/new': typeof ScriptsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/users': typeof SettingsUsersRoute
  '/shell-recordings/$sessionId': typeof ShellRecordingsSessionIdRoute
  '/a2a/': typeof A2aIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/alerts/': typeof AlertsIndexRoute
  '/checks/': typeof ChecksIndexRoute
  '/patches/': typeof PatchesIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shell-recordings/': typeof ShellRecordingsIndexRoute
  '/a2a/agents/$name': typeof A2aAgentsNameRoute
  '/a2a/tasks/$taskId': typeof A2aTasksTaskIdRoute
  '/agents/$agentId/shell': typeof AgentsAgentIdShellRoute
  '/scripts/$scriptId/runs/$runId': typeof ScriptsScriptIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/a2a/costs': typeof A2aCostsRoute
  '/a2a/tasks': typeof A2aTasksRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/checks/$checkId': typeof ChecksCheckIdRoute
  '/patches/$jobId': typeof PatchesJobIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRouteWithChildren
  '/scripts/new': typeof ScriptsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/users': typeof SettingsUsersRoute
  '/shell-recordings/$sessionId': typeof ShellRecordingsSessionIdRoute
  '/a2a': typeof A2aIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/alerts': typeof AlertsIndexRoute
  '/checks': typeof ChecksIndexRoute
  '/patches': typeof PatchesIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shell-recordings': typeof ShellRecordingsIndexRoute
  '/a2a/agents/$name': typeof A2aAgentsNameRoute
  '/a2a/tasks/$taskId': typeof A2aTasksTaskIdRoute
  '/agents/$agentId/shell': typeof AgentsAgentIdShellRoute
  '/scripts/$scriptId/runs/$runId': typeof ScriptsScriptIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/a2a/costs': typeof A2aCostsRoute
  '/a2a/tasks': typeof A2aTasksRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/checks/$checkId': typeof ChecksCheckIdRoute
  '/patches/$jobId': typeof PatchesJobIdRoute
  '/policies/$policyId': typeof PoliciesPolicyIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRouteWithChildren
  '/scripts/new': typeof ScriptsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/settings/users': typeof SettingsUsersRoute
  '/shell-recordings/$sessionId': typeof ShellRecordingsSessionIdRoute
  '/a2a/': typeof A2aIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/alerts/': typeof AlertsIndexRoute
  '/checks/': typeof ChecksIndexRoute
  '/patches/': typeof PatchesIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shell-recordings/': typeof ShellRecordingsIndexRoute
  '/a2a/agents/$name': typeof A2aAgentsNameRoute
  '/a2a/tasks/$taskId': typeof A2aTasksTaskIdRoute
  '/agents/$agentId/shell': typeof AgentsAgentIdShellRoute
  '/scripts/$scriptId/runs/$runId': typeof ScriptsScriptIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/a2a/costs'
    | '/a2a/tasks'
    | '/agents/$agentId'
    | '/alerts/$alertId'
    | '/checks/$checkId'
    | '/patches/$jobId'
    | '/policies/$policyId'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/sso'
    | '/settings/users'
    | '/shell-recordings/$sessionId'
    | '/a2a/'
    | '/agents/'
    | '/alerts/'
    | '/checks/'
    | '/patches/'
    | '/policies/'
    | '/scripts/'
    | '/settings/'
    | '/shell-recordings/'
    | '/a2a/agents/$name'
    | '/a2a/tasks/$taskId'
    | '/agents/$agentId/shell'
    | '/scripts/$scriptId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/a2a/costs'
    | '/a2a/tasks'
    | '/agents/$agentId'
    | '/alerts/$alertId'
    | '/checks/$checkId'
    | '/patches/$jobId'
    | '/policies/$policyId'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/sso'
    | '/settings/users'
    | '/shell-recordings/$sessionId'
    | '/a2a'
    | '/agents'
    | '/alerts'
    | '/checks'
    | '/patches'
    | '/policies'
    | '/scripts'
    | '/settings'
    | '/shell-recordings'
    | '/a2a/agents/$name'
    | '/a2a/tasks/$taskId'
    | '/agents/$agentId/shell'
    | '/scripts/$scriptId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/a2a/costs'
    | '/a2a/tasks'
    | '/agents/$agentId'
    | '/alerts/$alertId'
    | '/checks/$checkId'
    | '/patches/$jobId'
    | '/policies/$policyId'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/roles'
    | '/settings/sso'
    | '/settings/users'
    | '/shell-recordings/$sessionId'
    | '/a2a/'
    | '/agents/'
    | '/alerts/'
    | '/checks/'
    | '/patches/'
    | '/policies/'
    | '/scripts/'
    | '/settings/'
    | '/shell-recordings/'
    | '/a2a/agents/$name'
    | '/a2a/tasks/$taskId'
    | '/agents/$agentId/shell'
    | '/scripts/$scriptId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  A2aCostsRoute: typeof A2aCostsRoute
  A2aTasksRoute: typeof A2aTasksRouteWithChildren
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  ChecksCheckIdRoute: typeof ChecksCheckIdRoute
  PatchesJobIdRoute: typeof PatchesJobIdRoute
  PoliciesPolicyIdRoute: typeof PoliciesPolicyIdRoute
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRouteWithChildren
  ScriptsNewRoute: typeof ScriptsNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSsoRoute: typeof SettingsSsoRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  ShellRecordingsSessionIdRoute: typeof ShellRecordingsSessionIdRoute
  A2aIndexRoute: typeof A2aIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  ChecksIndexRoute: typeof ChecksIndexRoute
  PatchesIndexRoute: typeof PatchesIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ShellRecordingsIndexRoute: typeof ShellRecordingsIndexRoute
  A2aAgentsNameRoute: typeof A2aAgentsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell-recordings/': {
      id: '/shell-recordings/'
      path: '/shell-recordings'
      fullPath: '/shell-recordings/'
      preLoaderRoute: typeof ShellRecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patches/': {
      id: '/patches/'
      path: '/patches'
      fullPath: '/patches/'
      preLoaderRoute: typeof PatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks/': {
      id: '/checks/'
      path: '/checks'
      fullPath: '/checks/'
      preLoaderRoute: typeof ChecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a/': {
      id: '/a2a/'
      path: '/a2a'
      fullPath: '/a2a/'
      preLoaderRoute: typeof A2aIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell-recordings/$sessionId': {
      id: '/shell-recordings/$sessionId'
      path: '/shell-recordings/$sessionId'
      fullPath: '/shell-recordings/$sessionId'
      preLoaderRoute: typeof ShellRecordingsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sso': {
      id: '/settings/sso'
      path: '/settings/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof SettingsSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/new': {
      id: '/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policyId': {
      id: '/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof PoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patches/$jobId': {
      id: '/patches/$jobId'
      path: '/patches/$jobId'
      fullPath: '/patches/$jobId'
      preLoaderRoute: typeof PatchesJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks/$checkId': {
      id: '/checks/$checkId'
      path: '/checks/$checkId'
      fullPath: '/checks/$checkId'
      preLoaderRoute: typeof ChecksCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a/tasks': {
      id: '/a2a/tasks'
      path: '/a2a/tasks'
      fullPath: '/a2a/tasks'
      preLoaderRoute: typeof A2aTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a/costs': {
      id: '/a2a/costs'
      path: '/a2a/costs'
      fullPath: '/a2a/costs'
      preLoaderRoute: typeof A2aCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/shell': {
      id: '/agents/$agentId/shell'
      path: '/shell'
      fullPath: '/agents/$agentId/shell'
      preLoaderRoute: typeof AgentsAgentIdShellRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/a2a/tasks/$taskId': {
      id: '/a2a/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/a2a/tasks/$taskId'
      preLoaderRoute: typeof A2aTasksTaskIdRouteImport
      parentRoute: typeof A2aTasksRoute
    }
    '/a2a/agents/$name': {
      id: '/a2a/agents/$name'
      path: '/a2a/agents/$name'
      fullPath: '/a2a/agents/$name'
      preLoaderRoute: typeof A2aAgentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId/runs/$runId': {
      id: '/scripts/$scriptId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/scripts/$scriptId/runs/$runId'
      preLoaderRoute: typeof ScriptsScriptIdRunsRunIdRouteImport
      parentRoute: typeof ScriptsScriptIdRoute
    }
  }
}

interface A2aTasksRouteChildren {
  A2aTasksTaskIdRoute: typeof A2aTasksTaskIdRoute
}

const A2aTasksRouteChildren: A2aTasksRouteChildren = {
  A2aTasksTaskIdRoute: A2aTasksTaskIdRoute,
}

const A2aTasksRouteWithChildren = A2aTasksRoute._addFileChildren(
  A2aTasksRouteChildren,
)

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdShellRoute: typeof AgentsAgentIdShellRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdShellRoute: AgentsAgentIdShellRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

interface ScriptsScriptIdRouteChildren {
  ScriptsScriptIdRunsRunIdRoute: typeof ScriptsScriptIdRunsRunIdRoute
}

const ScriptsScriptIdRouteChildren: ScriptsScriptIdRouteChildren = {
  ScriptsScriptIdRunsRunIdRoute: ScriptsScriptIdRunsRunIdRoute,
}

const ScriptsScriptIdRouteWithChildren = ScriptsScriptIdRoute._addFileChildren(
  ScriptsScriptIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  A2aCostsRoute: A2aCostsRoute,
  A2aTasksRoute: A2aTasksRouteWithChildren,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  ChecksCheckIdRoute: ChecksCheckIdRoute,
  PatchesJobIdRoute: PatchesJobIdRoute,
  PoliciesPolicyIdRoute: PoliciesPolicyIdRoute,
  ScriptsScriptIdRoute: ScriptsScriptIdRouteWithChildren,
  ScriptsNewRoute: ScriptsNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSsoRoute: SettingsSsoRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  ShellRecordingsSessionIdRoute: ShellRecordingsSessionIdRoute,
  A2aIndexRoute: A2aIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  ChecksIndexRoute: ChecksIndexRoute,
  PatchesIndexRoute: PatchesIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ShellRecordingsIndexRoute: ShellRecordingsIndexRoute,
  A2aAgentsNameRoute: A2aAgentsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
