/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as LoginRoute } from './routes/login';
import { Route as IndexRoute } from './routes/index';
import { Route as SettingsRoute } from './routes/settings';
import { Route as DashboardRoute } from './routes/dashboard';
import { Route as AlertsIndexRoute } from './routes/alerts/index';
import { Route as AgentsIndexRoute } from './routes/agents/index';
import { Route as ChecksIndexRoute } from './routes/checks/index';
import { Route as PatchesIndexRoute } from './routes/patches/index';
import { Route as PoliciesIndexRoute } from './routes/policies/index';
import { Route as ScriptsIndexRoute } from './routes/scripts/index';
import { Route as ScriptsNewRoute } from './routes/scripts/new';
import { Route as AlertsAlertIdRoute } from './routes/alerts/$alertId';
import { Route as AgentsAgentIdRoute } from './routes/agents/$agentId';
import { Route as ChecksCheckIdRoute } from './routes/checks/$checkId';
import { Route as PatchesJobIdRoute } from './routes/patches/$jobId';
import { Route as PoliciesPolicyIdRoute } from './routes/policies/$policyId';
import { Route as ScriptsScriptIdRoute } from './routes/scripts/$scriptId';
import { Route as ScriptsScriptIdRunsRunIdRoute } from './routes/scripts/$scriptId/runs/$runId';

// Create/Update Routes

const LoginRouteRoute = createFileRoute('/login')({
  component: LoginRoute,
});

const IndexRouteRoute = createFileRoute('/')({
  component: IndexRoute,
});

const SettingsRouteRoute = createFileRoute('/settings')({
  component: SettingsRoute,
});

const DashboardRouteRoute = createFileRoute('/dashboard')({
  component: DashboardRoute,
});

const AlertsIndexRouteRoute = createFileRoute('/alerts/')({
  component: AlertsIndexRoute,
});

const AgentsIndexRouteRoute = createFileRoute('/agents/')({
  component: AgentsIndexRoute,
});

const ChecksIndexRouteRoute = createFileRoute('/checks/')({
  component: ChecksIndexRoute,
});

const PatchesIndexRouteRoute = createFileRoute('/patches/')({
  component: PatchesIndexRoute,
});

const PoliciesIndexRouteRoute = createFileRoute('/policies/')({
  component: PoliciesIndexRoute,
});

const ScriptsIndexRouteRoute = createFileRoute('/scripts/')({
  component: ScriptsIndexRoute,
});

const ScriptsNewRouteRoute = createFileRoute('/scripts/new')({
  component: ScriptsNewRoute,
});

const AlertsAlertIdRouteRoute = createFileRoute('/alerts/$alertId')({
  component: AlertsAlertIdRoute,
});

const AgentsAgentIdRouteRoute = createFileRoute('/agents/$agentId')({
  component: AgentsAgentIdRoute,
});

const ChecksCheckIdRouteRoute = createFileRoute('/checks/$checkId')({
  component: ChecksCheckIdRoute,
});

const PatchesJobIdRouteRoute = createFileRoute('/patches/$jobId')({
  component: PatchesJobIdRoute,
});

const PoliciesPolicyIdRouteRoute = createFileRoute('/policies/$policyId')({
  component: PoliciesPolicyIdRoute,
});

const ScriptsScriptIdRouteRoute = createFileRoute('/scripts/$scriptId')({
  component: ScriptsScriptIdRoute,
});

const ScriptsScriptIdRunsRunIdRouteRoute = createFileRoute(
  '/scripts/$scriptId/runs/$runId'
)({
  component: ScriptsScriptIdRunsRunIdRoute,
});

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRoute;
      parentRoute: typeof rootRoute;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/$agentId': {
      id: '/agents/$agentId';
      path: '/agents/$agentId';
      fullPath: '/agents/$agentId';
      preLoaderRoute: typeof AgentsAgentIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/alerts/$alertId': {
      id: '/alerts/$alertId';
      path: '/alerts/$alertId';
      fullPath: '/alerts/$alertId';
      preLoaderRoute: typeof AlertsAlertIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId';
      path: '/scripts/$scriptId';
      fullPath: '/scripts/$scriptId';
      preLoaderRoute: typeof ScriptsScriptIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/policies/$policyId': {
      id: '/policies/$policyId';
      path: '/policies/$policyId';
      fullPath: '/policies/$policyId';
      preLoaderRoute: typeof PoliciesPolicyIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/patches/$jobId': {
      id: '/patches/$jobId';
      path: '/patches/$jobId';
      fullPath: '/patches/$jobId';
      preLoaderRoute: typeof PatchesJobIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/checks/$checkId': {
      id: '/checks/$checkId';
      path: '/checks/$checkId';
      fullPath: '/checks/$checkId';
      preLoaderRoute: typeof ChecksCheckIdRoute;
      parentRoute: typeof rootRoute;
    };
    '/scripts/new': {
      id: '/scripts/new';
      path: '/scripts/new';
      fullPath: '/scripts/new';
      preLoaderRoute: typeof ScriptsNewRoute;
      parentRoute: typeof rootRoute;
    };
    '/scripts/': {
      id: '/scripts/';
      path: '/scripts';
      fullPath: '/scripts';
      preLoaderRoute: typeof ScriptsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/policies/': {
      id: '/policies/';
      path: '/policies';
      fullPath: '/policies';
      preLoaderRoute: typeof PoliciesIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/patches/': {
      id: '/patches/';
      path: '/patches';
      fullPath: '/patches';
      preLoaderRoute: typeof PatchesIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/checks/': {
      id: '/checks/';
      path: '/checks';
      fullPath: '/checks';
      preLoaderRoute: typeof ChecksIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/agents/': {
      id: '/agents/';
      path: '/agents';
      fullPath: '/agents';
      preLoaderRoute: typeof AgentsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/alerts/': {
      id: '/alerts/';
      path: '/alerts';
      fullPath: '/alerts';
      preLoaderRoute: typeof AlertsIndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/scripts/$scriptId/runs/$runId': {
      id: '/scripts/$scriptId/runs/$runId';
      path: '/scripts/$scriptId/runs/$runId';
      fullPath: '/scripts/$scriptId/runs/$runId';
      preLoaderRoute: typeof ScriptsScriptIdRunsRunIdRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute
  ._addFileChildren({
    ...IndexRouteRoute,
    ...LoginRouteRoute,
    ...DashboardRouteRoute,
    ...SettingsRouteRoute,
    ...AgentsIndexRouteRoute,
    ...AlertsIndexRouteRoute,
    ...ChecksIndexRouteRoute,
    ...PatchesIndexRouteRoute,
    ...PoliciesIndexRouteRoute,
    ...ScriptsIndexRouteRoute,
    ...ScriptsNewRouteRoute,
    ...AgentsAgentIdRouteRoute,
    ...AlertsAlertIdRouteRoute,
    ...ScriptsScriptIdRouteRoute,
    ...PoliciesPolicyIdRouteRoute,
    ...PatchesJobIdRouteRoute,
    ...ChecksCheckIdRouteRoute,
    ...ScriptsScriptIdRunsRunIdRouteRoute,
  })
  ._addFileTypes<any>();
