// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: a2a/spec/a2a.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED      TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING          TaskStatus = 1
	TaskStatus_TASK_STATUS_WORKING          TaskStatus = 2
	TaskStatus_TASK_STATUS_INPUT_REQUIRED   TaskStatus = 3
	TaskStatus_TASK_STATUS_OUTPUT_AVAILABLE TaskStatus = 4
	TaskStatus_TASK_STATUS_COMPLETED        TaskStatus = 5
	TaskStatus_TASK_STATUS_FAILED           TaskStatus = 6
	TaskStatus_TASK_STATUS_CANCELLED        TaskStatus = 7
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_WORKING",
		3: "TASK_STATUS_INPUT_REQUIRED",
		4: "TASK_STATUS_OUTPUT_AVAILABLE",
		5: "TASK_STATUS_COMPLETED",
		6: "TASK_STATUS_FAILED",
		7: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":      0,
		"TASK_STATUS_PENDING":          1,
		"TASK_STATUS_WORKING":          2,
		"TASK_STATUS_INPUT_REQUIRED":   3,
		"TASK_STATUS_OUTPUT_AVAILABLE": 4,
		"TASK_STATUS_COMPLETED":        5,
		"TASK_STATUS_FAILED":           6,
		"TASK_STATUS_CANCELLED":        7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_a2a_spec_a2a_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_a2a_spec_a2a_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{0}
}

type AgentCard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version            string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Framework          string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Endpoint           string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capabilities       []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Tags               []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Skills             []*Skill               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Authentication     *AuthScheme            `protobuf:"bytes,10,opt,name=authentication,proto3" json:"authentication,omitempty"`
	ProviderName       string                 `protobuf:"bytes,11,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderUrl        string                 `protobuf:"bytes,12,opt,name=provider_url,json=providerUrl,proto3" json:"provider_url,omitempty"`
	Streaming          bool                   `protobuf:"varint,13,opt,name=streaming,proto3" json:"streaming,omitempty"`
	PushNotifications  bool                   `protobuf:"varint,14,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	DefaultInputModes  []string               `protobuf:"bytes,15,rep,name=default_input_modes,json=defaultInputModes,proto3" json:"default_input_modes,omitempty"`
	DefaultOutputModes []string               `protobuf:"bytes,16,rep,name=default_output_modes,json=defaultOutputModes,proto3" json:"default_output_modes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *AgentCard) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AgentCard) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentCard) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCard) GetAuthentication() *AuthScheme {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *AgentCard) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *AgentCard) GetProviderUrl() string {
	if x != nil {
		return x.ProviderUrl
	}
	return ""
}

func (x *AgentCard) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *AgentCard) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *AgentCard) GetDefaultInputModes() []string {
	if x != nil {
		return x.DefaultInputModes
	}
	return nil
}

func (x *AgentCard) GetDefaultOutputModes() []string {
	if x != nil {
		return x.DefaultOutputModes
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{1}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AuthScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // bearer, mtls, oauth2
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthScheme) Reset() {
	*x = AuthScheme{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthScheme) ProtoMessage() {}

func (x *AuthScheme) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthScheme.ProtoReflect.Descriptor instead.
func (*AuthScheme) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{2}
}

func (x *AuthScheme) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthScheme) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Part_Text
	//	*Part_File
	//	*Part_Data
	Content       isPart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{3}
}

func (x *Part) GetContent() isPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetFile() *FileRef {
	if x != nil {
		if x, ok := x.Content.(*Part_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Part) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPart_Content interface {
	isPart_Content()
}

type Part_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_File struct {
	File *FileRef `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

type Part_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*Part_Text) isPart_Content() {}

func (*Part_File) isPart_Content() {}

func (*Part_Data) isPart_Content() {}

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{4}
}

func (x *FileRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // user, agent, system
	Parts         []*Part                `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Parts         []*Part                `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{6}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artifact) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=a2a.v1.TaskStatus" json:"status,omitempty"`
	Message       *Message               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=a2a.v1.TaskStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStatusUpdate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SendTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskRequest) Reset() {
	*x = SendTaskRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskRequest) ProtoMessage() {}

func (x *SendTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskRequest.ProtoReflect.Descriptor instead.
func (*SendTaskRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{9}
}

func (x *SendTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type SendTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskResponse) Reset() {
	*x = SendTaskResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskResponse) ProtoMessage() {}

func (x *SendTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskResponse.ProtoReflect.Descriptor instead.
func (*SendTaskResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{10}
}

func (x *SendTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{14}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTaskRequest) Reset() {
	*x = SubscribeTaskRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTaskRequest) ProtoMessage() {}

func (x *SubscribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTaskRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *AgentCard             `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterAgentRequest) GetCard() *AgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *AgentCard             `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterAgentResponse) GetCard() *AgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{20}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentCard           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_a2a_spec_a2a_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2a_spec_a2a_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_a2a_spec_a2a_proto_rawDescGZIP(), []int{21}
}

func (x *ListAgentsResponse) GetAgents() []*AgentCard {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_a2a_spec_a2a_proto protoreflect.FileDescriptor

const file_a2a_spec_a2a_proto_rawDesc = "" +
	"\n" +
	"\x12a2a/spec/a2a.proto\x12\x06a2a.v1\"\xb7\x04\n" +
	"\tAgentCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12%\n" +
	"\x06skills\x18\t \x03(\v2\r.a2a.v1.SkillR\x06skills\x12:\n" +
	"\x0eauthentication\x18\n" +
	" \x01(\v2\x12.a2a.v1.AuthSchemeR\x0eauthentication\x12#\n" +
	"\rprovider_name\x18\v \x01(\tR\fproviderName\x12!\n" +
	"\fprovider_url\x18\f \x01(\tR\vproviderUrl\x12\x1c\n" +
	"\tstreaming\x18\r \x01(\bR\tstreaming\x12-\n" +
	"\x12push_notifications\x18\x0e \x01(\bR\x11pushNotifications\x12.\n" +
	"\x13default_input_modes\x18\x0f \x03(\tR\x11defaultInputModes\x120\n" +
	"\x14default_output_modes\x18\x10 \x03(\tR\x12defaultOutputModes\"a\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x93\x01\n" +
	"\n" +
	"AuthScheme\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x126\n" +
	"\x06config\x18\x02 \x03(\v2\x1e.a2a.v1.AuthScheme.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12%\n" +
	"\x04file\x18\x02 \x01(\v2\x0f.a2a.v1.FileRefH\x00R\x04file\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontent\"L\n" +
	"\aFileRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"Q\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\x05parts\x18\x03 \x03(\v2\f.a2a.v1.PartR\x05parts\"\xc9\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\x05parts\x18\x05 \x03(\v2\f.a2a.v1.PartR\x05parts\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xa4\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.a2a.v1.TaskStatusR\x06status\x12)\n" +
	"\amessage\x18\x05 \x01(\v2\x0f.a2a.v1.MessageR\amessage\x12.\n" +
	"\tartifacts\x18\x06 \x03(\v2\x10.a2a.v1.ArtifactR\tartifacts\x126\n" +
	"\bmetadata\x18\a \x03(\v2\x1a.a2a.v1.Task.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.a2a.v1.TaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"3\n" +
	"\x0fSendTaskRequest\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.a2a.v1.TaskR\x04task\"4\n" +
	"\x10SendTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.a2a.v1.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"3\n" +
	"\x0fGetTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.a2a.v1.TaskR\x04task\"\x92\x01\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"M\n" +
	"\x11ListTasksResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.a2a.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14SubscribeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"=\n" +
	"\x14RegisterAgentRequest\x12%\n" +
	"\x04card\x18\x01 \x01(\v2\x11.a2a.v1.AgentCardR\x04card\">\n" +
	"\x15RegisterAgentResponse\x12%\n" +
	"\x04card\x18\x01 \x01(\v2\x11.a2a.v1.AgentCardR\x04card\"\x13\n" +
	"\x11ListAgentsRequest\"?\n" +
	"\x12ListAgentsResponse\x12)\n" +
	"\x06agents\x18\x01 \x03(\v2\x11.a2a.v1.AgentCardR\x06agents*\xeb\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_WORKING\x10\x02\x12\x1e\n" +
	"\x1aTASK_STATUS_INPUT_REQUIRED\x10\x03\x12 \n" +
	"\x1cTASK_STATUS_OUTPUT_AVAILABLE\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x05\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\a2\xb6\x04\n" +
	"\n" +
	"A2AService\x12=\n" +
	"\bSendTask\x12\x17.a2a.v1.SendTaskRequest\x1a\x18.a2a.v1.SendTaskResponse\x12:\n" +
	"\aGetTask\x12\x16.a2a.v1.GetTaskRequest\x1a\x17.a2a.v1.GetTaskResponse\x12@\n" +
	"\tListTasks\x12\x18.a2a.v1.ListTasksRequest\x1a\x19.a2a.v1.ListTasksResponse\x12C\n" +
	"\n" +
	"CancelTask\x12\x19.a2a.v1.CancelTaskRequest\x1a\x1a.a2a.v1.CancelTaskResponse\x12H\n" +
	"\x11SendSubscribeTask\x12\x17.a2a.v1.SendTaskRequest\x1a\x18.a2a.v1.TaskStatusUpdate0\x01\x12I\n" +
	"\rSubscribeTask\x12\x1c.a2a.v1.SubscribeTaskRequest\x1a\x18.a2a.v1.TaskStatusUpdate0\x01\x12L\n" +
	"\rRegisterAgent\x12\x1c.a2a.v1.RegisterAgentRequest\x1a\x1d.a2a.v1.RegisterAgentResponse\x12C\n" +
	"\n" +
	"ListAgents\x12\x19.a2a.v1.ListAgentsRequest\x1a\x1a.a2a.v1.ListAgentsResponseB9Z7github.com/openagentplatform/openagentplatform/a2a/specb\x06proto3"

var (
	file_a2a_spec_a2a_proto_rawDescOnce sync.Once
	file_a2a_spec_a2a_proto_rawDescData []byte
)

func file_a2a_spec_a2a_proto_rawDescGZIP() []byte {
	file_a2a_spec_a2a_proto_rawDescOnce.Do(func() {
		file_a2a_spec_a2a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_a2a_spec_a2a_proto_rawDesc), len(file_a2a_spec_a2a_proto_rawDesc)))
	})
	return file_a2a_spec_a2a_proto_rawDescData
}

var file_a2a_spec_a2a_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_a2a_spec_a2a_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_a2a_spec_a2a_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: a2a.v1.TaskStatus
	(*AgentCard)(nil),             // 1: a2a.v1.AgentCard
	(*Skill)(nil),                 // 2: a2a.v1.Skill
	(*AuthScheme)(nil),            // 3: a2a.v1.AuthScheme
	(*Part)(nil),                  // 4: a2a.v1.Part
	(*FileRef)(nil),               // 5: a2a.v1.FileRef
	(*Message)(nil),               // 6: a2a.v1.Message
	(*Artifact)(nil),              // 7: a2a.v1.Artifact
	(*Task)(nil),                  // 8: a2a.v1.Task
	(*TaskStatusUpdate)(nil),      // 9: a2a.v1.TaskStatusUpdate
	(*SendTaskRequest)(nil),       // 10: a2a.v1.SendTaskRequest
	(*SendTaskResponse)(nil),      // 11: a2a.v1.SendTaskResponse
	(*GetTaskRequest)(nil),        // 12: a2a.v1.GetTaskRequest
	(*GetTaskResponse)(nil),       // 13: a2a.v1.GetTaskResponse
	(*ListTasksRequest)(nil),      // 14: a2a.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 15: a2a.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),     // 16: a2a.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 17: a2a.v1.CancelTaskResponse
	(*SubscribeTaskRequest)(nil),  // 18: a2a.v1.SubscribeTaskRequest
	(*RegisterAgentRequest)(nil),  // 19: a2a.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 20: a2a.v1.RegisterAgentResponse
	(*ListAgentsRequest)(nil),     // 21: a2a.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 22: a2a.v1.ListAgentsResponse
	nil,                           // 23: a2a.v1.AuthScheme.ConfigEntry
	nil,                           // 24: a2a.v1.Task.MetadataEntry
}
var file_a2a_spec_a2a_proto_depIdxs = []int32{
	2,  // 0: a2a.v1.AgentCard.skills:type_name -> a2a.v1.Skill
	3,  // 1: a2a.v1.AgentCard.authentication:type_name -> a2a.v1.AuthScheme
	23, // 2: a2a.v1.AuthScheme.config:type_name -> a2a.v1.AuthScheme.ConfigEntry
	5,  // 3: a2a.v1.Part.file:type_name -> a2a.v1.FileRef
	4,  // 4: a2a.v1.Message.parts:type_name -> a2a.v1.Part
	4,  // 5: a2a.v1.Artifact.parts:type_name -> a2a.v1.Part
	0,  // 6: a2a.v1.Task.status:type_name -> a2a.v1.TaskStatus
	6,  // 7: a2a.v1.Task.message:type_name -> a2a.v1.Message
	7,  // 8: a2a.v1.Task.artifacts:type_name -> a2a.v1.Artifact
	24, // 9: a2a.v1.Task.metadata:type_name -> a2a.v1.Task.MetadataEntry
	0,  // 10: a2a.v1.TaskStatusUpdate.status:type_name -> a2a.v1.TaskStatus
	8,  // 11: a2a.v1.SendTaskRequest.task:type_name -> a2a.v1.Task
	8,  // 12: a2a.v1.SendTaskResponse.task:type_name -> a2a.v1.Task
	8,  // 13: a2a.v1.GetTaskResponse.task:type_name -> a2a.v1.Task
	8,  // 14: a2a.v1.ListTasksResponse.tasks:type_name -> a2a.v1.Task
	1,  // 15: a2a.v1.RegisterAgentRequest.card:type_name -> a2a.v1.AgentCard
	1,  // 16: a2a.v1.RegisterAgentResponse.card:type_name -> a2a.v1.AgentCard
	1,  // 17: a2a.v1.ListAgentsResponse.agents:type_name -> a2a.v1.AgentCard
	10, // 18: a2a.v1.A2AService.SendTask:input_type -> a2a.v1.SendTaskRequest
	12, // 19: a2a.v1.A2AService.GetTask:input_type -> a2a.v1.GetTaskRequest
	14, // 20: a2a.v1.A2AService.ListTasks:input_type -> a2a.v1.ListTasksRequest
	16, // 21: a2a.v1.A2AService.CancelTask:input_type -> a2a.v1.CancelTaskRequest
	10, // 22: a2a.v1.A2AService.SendSubscribeTask:input_type -> a2a.v1.SendTaskRequest
	18, // 23: a2a.v1.A2AService.SubscribeTask:input_type -> a2a.v1.SubscribeTaskRequest
	19, // 24: a2a.v1.A2AService.RegisterAgent:input_type -> a2a.v1.RegisterAgentRequest
	21, // 25: a2a.v1.A2AService.ListAgents:input_type -> a2a.v1.ListAgentsRequest
	11, // 26: a2a.v1.A2AService.SendTask:output_type -> a2a.v1.SendTaskResponse
	13, // 27: a2a.v1.A2AService.GetTask:output_type -> a2a.v1.GetTaskResponse
	15, // 28: a2a.v1.A2AService.ListTasks:output_type -> a2a.v1.ListTasksResponse
	17, // 29: a2a.v1.A2AService.CancelTask:output_type -> a2a.v1.CancelTaskResponse
	9,  // 30: a2a.v1.A2AService.SendSubscribeTask:output_type -> a2a.v1.TaskStatusUpdate
	9,  // 31: a2a.v1.A2AService.SubscribeTask:output_type -> a2a.v1.TaskStatusUpdate
	20, // 32: a2a.v1.A2AService.RegisterAgent:output_type -> a2a.v1.RegisterAgentResponse
	22, // 33: a2a.v1.A2AService.ListAgents:output_type -> a2a.v1.ListAgentsResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_a2a_spec_a2a_proto_init() }
func file_a2a_spec_a2a_proto_init() {
	if File_a2a_spec_a2a_proto != nil {
		return
	}
	file_a2a_spec_a2a_proto_msgTypes[3].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_File)(nil),
		(*Part_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_a2a_spec_a2a_proto_rawDesc), len(file_a2a_spec_a2a_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a2a_spec_a2a_proto_goTypes,
		DependencyIndexes: file_a2a_spec_a2a_proto_depIdxs,
		EnumInfos:         file_a2a_spec_a2a_proto_enumTypes,
		MessageInfos:      file_a2a_spec_a2a_proto_msgTypes,
	}.Build()
	File_a2a_spec_a2a_proto = out.File
	file_a2a_spec_a2a_proto_goTypes = nil
	file_a2a_spec_a2a_proto_depIdxs = nil
}
